import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";

// Load environment variables from .env.local
dotenv.config({ path: ".env.local" });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
// Use service_role key for seed script to bypass RLS
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

const supabase = createClient(supabaseUrl, supabaseKey);

// فئات التجميل فقط
const categories = [
  {
    name_ar: "العناية بالبشرة",
    name_en: "Skincare",
    description_ar: "منتجات العناية بالبشرة الطبيعية والصحية",
    description_en: "Natural and healthy skincare products",
    color: "#F8BBD0", // وردي ناعم
  },
  {
    name_ar: "المكياج",
    name_en: "Makeup",
    description_ar: "مجموعة واسعة من منتجات المكياج عالية الجودة",
    description_en: "Wide range of high-quality makeup products",
    color: "#FFD6CC", // خوخي
  },
  {
    name_ar: "العناية بالشعر",
    name_en: "Hair Care",
    description_ar: "منتجات العناية بالشعر والتجميل",
    description_en: "Hair care and styling products",
    color: "#E6D5F3", // لافندر
  },
  {
    name_ar: "العطور",
    name_en: "Fragrance",
    description_ar: "عطور فاخرة بروائح مميزة",
    description_en: "Luxury fragrances with distinctive scents",
    color: "#FFC4B3", // خوخي فاتح
  },
  {
    name_ar: "العناية بالجسم",
    name_en: "Body Care",
    description_ar: "منتجات العناية بالجسم والاستحمام",
    description_en: "Body care and bath products",
    color: "#D4B5E8", // لافندر فاتح
  },
  {
    name_ar: "أدوات التجميل",
    name_en: "Beauty Tools",
    description_ar: "أدوات ومستلزمات التجميل الاحترافية",
    description_en: "Professional beauty tools and accessories",
    color: "#F5A6C0", // وردي متوسط
  },
];

// منتجات تجميل حقيقية
const products = [
  // العناية بالبشرة (10 منتجات)
  {
    name_ar: "مرطب للوجه",
    name_en: "Face Moisturizer",
    description_ar: "مرطب للوجه بتركيبة طبيعية للبشرة الجافة والعادية",
    description_en: "Face moisturizer with natural formula for dry and normal skin",
    price: 89.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw91979480/ProductImages/Face/Rouge_Cream_Blush/rougecreamblush_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 120,
    rating: 4.6,
    category: "Skincare",
  },
  {
    name_ar: "ماسك للوجه",
    name_en: "Face Mask",
    description_ar: "ماسك للوجه من الطين الطبيعي لتنظيف البشرة",
    description_en: "Natural clay face mask for deep cleansing",
    price: 49.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/268da4d7967fad9c153af24ee8d2e026_ra,w158,h184_pa,w158,h184.jpg",
    available_quantity: 150,
    rating: 4.5,
    category: "Skincare",
  },
  {
    name_ar: "مستحضر تنظيف البشرة",
    name_en: "Face Cleanser",
    description_ar: "مستحضر تنظيف البشرة الطبيعي الخالي من المواد الكيميائية",
    description_en: "Natural face cleanser free from harsh chemicals",
    price: 59.99,
    image_url: "https://static-assets.glossier.com/production/spree/images/attachments/000/000/726/portrait_normal/PST_Carousel_02-compressor.jpg?1470088244",
    available_quantity: 110,
    rating: 4.7,
    category: "Skincare",
  },
  {
    name_ar: "سيروم فيتامين سي",
    name_en: "Vitamin C Serum",
    description_ar: "سيروم فيتامين سي لتفتيح البشرة وتوحيد اللون",
    description_en: "Vitamin C serum for brightening and evening skin tone",
    price: 129.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/39be9facd53cf124ff38e9a25de09e10_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 85,
    rating: 4.8,
    category: "Skincare",
  },
  {
    name_ar: "كريم واقي من الشمس",
    name_en: "Sunscreen",
    description_ar: "كريم واقي من الشمس بمعامل حماية عالي SPF 50",
    description_en: "High SPF 50 sunscreen for maximum protection",
    price: 69.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/cca454e907546544ca9b5b183bb8a96c_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 140,
    rating: 4.6,
    category: "Skincare",
  },
  {
    name_ar: "تونر للبشرة",
    name_en: "Face Toner",
    description_ar: "تونر منعش للبشرة لتنظيف المسام",
    description_en: "Refreshing face toner for pore cleansing",
    price: 54.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/3c711478d1b8a9f1c7d9f2c1cdffdb41_ra,w158,h184_pa,w158,h184.png",
    available_quantity: 100,
    rating: 4.5,
    category: "Skincare",
  },
  {
    name_ar: "كريم العين",
    name_en: "Eye Cream",
    description_ar: "كريم العين المضاد للتجاعيد والهالات السوداء",
    description_en: "Anti-aging eye cream for wrinkles and dark circles",
    price: 99.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwc135311a/ProductImages/2018/Eyes/Holographic_Halo_Cream_Liner/holographichalocreamliner_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 95,
    rating: 4.7,
    category: "Skincare",
  },
  {
    name_ar: "مصل النياسيناميد",
    name_en: "Niacinamide Serum",
    description_ar: "مصل النياسيناميد لتنظيم إفراز الدهون وتقليل المسام",
    description_en: "Niacinamide serum for oil control and pore reduction",
    price: 79.99,
    image_url: "https://static-assets.glossier.com/production/spree/images/attachments/000/001/631/portrait_normal/SC_Carousel_1_copy_2.jpg?1506948615",
    available_quantity: 105,
    rating: 4.6,
    category: "Skincare",
  },
  {
    name_ar: "مقشر للبشرة",
    name_en: "Face Scrub",
    description_ar: "مقشر لطيف للبشرة لإزالة الخلايا الميتة",
    description_en: "Gentle face scrub for removing dead skin cells",
    price: 44.99,
    image_url: "https://static-assets.glossier.com/production/spree/images/attachments/000/001/476/portrait_normal/carousel-1.jpg?1501534121",
    available_quantity: 130,
    rating: 4.4,
    category: "Skincare",
  },
  {
    name_ar: "كريم ليلي",
    name_en: "Night Cream",
    description_ar: "كريم ليلي مغذي للبشرة لإصلاحها أثناء النوم",
    description_en: "Nourishing night cream for skin repair during sleep",
    price: 109.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwa8106b14/ProductImages/Face/BB_Cream/800897822927_bbcream_natural_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 90,
    rating: 4.8,
    category: "Skincare",
  },
  // المكياج (10 منتجات)
  {
    name_ar: "أحمر شفاه",
    name_en: "Lipstick",
    description_ar: "أحمر شفاه طويل الأمد بألوان متنوعة ومتألقة",
    description_en: "Long-lasting lipstick in various vibrant colors",
    price: 39.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw063995a2/ProductImages/2017/Lips/Luv_Out_Loud_Liquid_Lipstick/luvoutloudliquidlipstick_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 200,
    rating: 4.5,
    category: "Makeup",
  },
  {
    name_ar: "ماسكارا",
    name_en: "Mascara",
    description_ar: "ماسكارا لتكثيف وإطالة الرموش",
    description_en: "Mascara for volumizing and lengthening lashes",
    price: 49.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/e4bd2eaff5e2b0c9c8c29ecd86d0c7e6_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 180,
    rating: 4.6,
    category: "Makeup",
  },
  {
    name_ar: "كونسيلر",
    name_en: "Concealer",
    description_ar: "كونسيلر عالي التغطية لإخفاء العيوب والهالات",
    description_en: "High coverage concealer for hiding imperfections and dark circles",
    price: 54.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw947da0d5/ProductImages/Face/Gotcha_Covered_Concealer/gotchacoveredconcealer_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 160,
    rating: 4.7,
    category: "Makeup",
  },
  {
    name_ar: "بودرة الوجه",
    name_en: "Face Powder",
    description_ar: "بودرة شفافة لتثبيت المكياج وإزالة اللمعان",
    description_en: "Translucent face powder for setting makeup and reducing shine",
    price: 44.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw3aaafbb3/ProductImages/Face/Studio_Finishing_Powder/studiofinishingpowder_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 170,
    rating: 4.5,
    category: "Makeup",
  },
  {
    name_ar: "أحمر خدود",
    name_en: "Blush",
    description_ar: "أحمر خدود بألوان ناعمة لإضافة لون طبيعي للوجنتين",
    description_en: "Soft blush for adding natural color to cheeks",
    price: 34.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwa0a9cf48/ProductImages/2016/Face/Sweet_Cheeks_Blush_Palette/sweetcheeksblushpalette_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 190,
    rating: 4.4,
    category: "Makeup",
  },
  {
    name_ar: "ظلال العيون",
    name_en: "Eyeshadow Palette",
    description_ar: "لوحة ظلال عيون بألوان متناسقة ومتعددة",
    description_en: "Eyeshadow palette with coordinated multiple colors",
    price: 79.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/e8be715d17f0bcc25ffe81f4286ffac0_ra,w158,h184_pa,w158,h184.png",
    available_quantity: 140,
    rating: 4.6,
    category: "Makeup",
  },
  {
    name_ar: "آيلاينر",
    name_en: "Eyeliner",
    description_ar: "آيلاينر سائل لرسم خط عين مثالي",
    description_en: "Liquid eyeliner for perfect eye line",
    price: 29.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw1a50507a/ProductImages/2018/Eyes/Metallic_Eyeliner/metalliceyeliner_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 210,
    rating: 4.5,
    category: "Makeup",
  },
  {
    name_ar: "برايمر للوجه",
    name_en: "Face Primer",
    description_ar: "برايمر لتجهيز البشرة قبل المكياج",
    description_en: "Face primer for preparing skin before makeup",
    price: 64.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/04c6f1353fdaf82d48a9d3ecf0d619f4_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 125,
    rating: 4.7,
    category: "Makeup",
  },
  {
    name_ar: "مجموعة مكياج كاملة",
    name_en: "Complete Makeup Set",
    description_ar: "مجموعة مكياج كاملة بجميع الأدوات الأساسية",
    description_en: "Complete makeup set with all essential tools",
    price: 199.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/e48da5acde28bd3b1bcc2bff5b9d4a56_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 60,
    rating: 4.8,
    category: "Makeup",
  },
  {
    name_ar: "كحل",
    name_en: "Kohl",
    description_ar: "كحل طبيعي للعيون بتقليد عربي أصيل",
    description_en: "Natural kohl for eyes with authentic Arabic tradition",
    price: 24.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/0e085149c3fbedd0aa6661c6b3d143cf_ra,w158,h184_pa,w158,h184.jpg",
    available_quantity: 220,
    rating: 4.6,
    category: "Makeup",
  },
  // العناية بالشعر (10 منتجات)
  {
    name_ar: "شامبو طبيعي",
    name_en: "Natural Shampoo",
    description_ar: "شامبو طبيعي للعناية بالشعر بدون كبريتات",
    description_en: "Natural sulfate-free shampoo for hair care",
    price: 39.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/c77ad2da76259cfd67a9a9432f635bfb_ra,w158,h184_pa,w158,h184.png",
    available_quantity: 180,
    rating: 4.5,
    category: "Hair Care",
  },
  {
    name_ar: "بلسم للشعر",
    name_en: "Hair Conditioner",
    description_ar: "بلسم للشعر يمنحه لمعاناً ونعومة فائقة",
    description_en: "Hair conditioner that gives shine and extra softness",
    price: 44.99,
    image_url: "https://static-assets.glossier.com/production/spree/images/attachments/000/001/109/portrait_normal/Haloscope_01-compressor.jpg?1498613775",
    available_quantity: 165,
    rating: 4.6,
    category: "Hair Care",
  },
  {
    name_ar: "مصل للشعر",
    name_en: "Hair Serum",
    description_ar: "مصل للشعر لحماية من الحرارة وإصلاح الأطراف",
    description_en: "Hair serum for heat protection and split end repair",
    price: 69.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/700e432a504f4784792e84d498c982b7_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 145,
    rating: 4.7,
    category: "Hair Care",
  },
  {
    name_ar: "قناع للشعر",
    name_en: "Hair Mask",
    description_ar: "قناع للشعر المغذي لإصلاح الشعر التالف",
    description_en: "Nourishing hair mask for repairing damaged hair",
    price: 59.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/369c6a7dc5ce002dd66b2271256b84c9_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 130,
    rating: 4.6,
    category: "Hair Care",
  },
  {
    name_ar: "زيت للشعر",
    name_en: "Hair Oil",
    description_ar: "زيت طبيعي للشعر لترطيبه وتغذيته",
    description_en: "Natural hair oil for moisturizing and nourishing",
    price: 54.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/844f8a41bfd962e75295db3b75ad3167_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 150,
    rating: 4.5,
    category: "Hair Care",
  },
  {
    name_ar: "سبراي للشعر",
    name_en: "Hair Spray",
    description_ar: "سبراي لتثبيت التسريحة وحماية الشعر",
    description_en: "Hair spray for holding style and protecting hair",
    price: 34.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/ccb99ad6ac7f31a2a73454bdbda01d99_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 200,
    rating: 4.4,
    category: "Hair Care",
  },
  {
    name_ar: "علاج للشعر",
    name_en: "Hair Treatment",
    description_ar: "علاج عميق للشعر لإصلاحه وتقويته",
    description_en: "Deep hair treatment for repair and strengthening",
    price: 89.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwd3ce6c29/ProductImages/2016/More/SFX_Setting_Powder/sfxsettingpowder_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 110,
    rating: 4.7,
    category: "Hair Care",
  },
  {
    name_ar: "شامبو جاف",
    name_en: "Dry Shampoo",
    description_ar: "شامبو جاف لتنظيف الشعر السريع بدون ماء",
    description_en: "Dry shampoo for quick hair cleaning without water",
    price: 29.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/19422d63bf6e51c128bc2fa457fa61dc_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 190,
    rating: 4.5,
    category: "Hair Care",
  },
  {
    name_ar: "كريم للشعر",
    name_en: "Hair Cream",
    description_ar: "كريم للشعر لتسريحه وتنعيمه",
    description_en: "Hair cream for styling and smoothing",
    price: 49.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/4ca356be704dce025868182946e52080_ra,w158,h184_pa,w158,h184.jpg",
    available_quantity: 160,
    rating: 4.6,
    category: "Hair Care",
  },
  {
    name_ar: "مجموعة العناية بالشعر",
    name_en: "Hair Care Set",
    description_ar: "مجموعة كاملة للعناية بالشعر",
    description_en: "Complete hair care set",
    price: 149.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/7fb45dded4fbe7603a9aa9f56a65eeca_ra,w158,h184_pa,w158,h184.png",
    available_quantity: 75,
    rating: 4.8,
    category: "Hair Care",
  },
  // العطور (10 منتجات)
  {
    name_ar: "عطر نسائي فاخر",
    name_en: "Luxury Women's Perfume",
    description_ar: "عطر نسائي فاخر برائحة زهرية مميزة",
    description_en: "Luxury women's perfume with distinctive floral scent",
    price: 299.99,
    image_url: "https://cdn.shopify.com/s/files/1/1338/0845/products/brain-freeze_a_800x1200.jpg?v=1502255076",
    available_quantity: 50,
    rating: 4.8,
    category: "Fragrance",
  },
  {
    name_ar: "عطر رجالي",
    name_en: "Men's Cologne",
    description_ar: "عطر رجالي برائحة قوية ومميزة",
    description_en: "Men's cologne with strong and distinctive scent",
    price: 249.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw1f4a57e0/ProductImages/Face/Blotting_Powder/800897822620_blottingpowder_light_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 60,
    rating: 4.7,
    category: "Fragrance",
  },
  {
    name_ar: "عطر زهري",
    name_en: "Floral Perfume",
    description_ar: "عطر برائحة زهرية ناعمة وأنثوية",
    description_en: "Perfume with soft and feminine floral scent",
    price: 179.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/4c9db52b5d1cf54fe74fc60b00ffdaa1_ra,w158,h184_pa,w158,h184.png",
    available_quantity: 80,
    rating: 4.6,
    category: "Fragrance",
  },
  {
    name_ar: "عطر عود",
    name_en: "Oud Perfume",
    description_ar: "عطر عود أصيل برائحة شرقية مميزة",
    description_en: "Authentic oud perfume with distinctive oriental scent",
    price: 399.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw2945b62d/ProductImages/2018/Face/Holographic_Halo_Finishing_Powder/holographichalofinishingpowder_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 40,
    rating: 4.9,
    category: "Fragrance",
  },
  {
    name_ar: "عطر حلو",
    name_en: "Sweet Perfume",
    description_ar: "عطر برائحة حلوة وفواكهية",
    description_en: "Perfume with sweet and fruity scent",
    price: 159.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw21376be0/ProductImages/2018/Lips/Soft_Matte_Metallic_Lip_Cream/softmattelipcream_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 90,
    rating: 4.5,
    category: "Fragrance",
  },
  {
    name_ar: "عطر منعش",
    name_en: "Fresh Perfume",
    description_ar: "عطر منعش برائحة الحمضيات",
    description_en: "Fresh perfume with citrus scent",
    price: 139.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw63a5fdce/ProductImages/2017/Face/High_Definition_Finishing_Powder_Mini/800897846015_highdefinitionfinishingpowdermini_translucent_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 100,
    rating: 4.6,
    category: "Fragrance",
  },
  {
    name_ar: "عطر رومانسي",
    name_en: "Romantic Perfume",
    description_ar: "عطر رومانسي برائحة الفانيليا والورد",
    description_en: "Romantic perfume with vanilla and rose scent",
    price: 219.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwb9e0511a/ProductImages/2016/Face/Cheek_Contour_Duo_Palette/800897012007_cheekcontourduopalette_doubledate_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 70,
    rating: 4.7,
    category: "Fragrance",
  },
  {
    name_ar: "عطر ناعم",
    name_en: "Soft Perfume",
    description_ar: "عطر ناعم برائحة المسك والياسمين",
    description_en: "Soft perfume with musk and jasmine scent",
    price: 189.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw663a4cdb/ProductImages/Lips/Soft_Matte_Lip_Cream/softmattelipcream_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 85,
    rating: 4.6,
    category: "Fragrance",
  },
  {
    name_ar: "عطر كلاسيكي",
    name_en: "Classic Perfume",
    description_ar: "عطر كلاسيكي برائحة تقليدية أنيقة",
    description_en: "Classic perfume with elegant traditional scent",
    price: 269.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwd7e25eb8/ProductImages/2016/Face/No_Filter_Finishing_Powder/nofilterfinishingpowder_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 55,
    rating: 4.8,
    category: "Fragrance",
  },
  {
    name_ar: "عطر يومي",
    name_en: "Daily Perfume",
    description_ar: "عطر خفيف مناسب للاستخدام اليومي",
    description_en: "Light perfume suitable for daily use",
    price: 119.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw78639528/ProductImages/Face/Color_Correcting_Powder/colorcorrectingpowder_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 120,
    rating: 4.5,
    category: "Fragrance",
  },
  // العناية بالجسم (10 منتجات)
  {
    name_ar: "لوشن للجسم",
    name_en: "Body Lotion",
    description_ar: "لوشن للجسم لترطيب البشرة ونعومتها",
    description_en: "Body lotion for moisturizing and softening skin",
    price: 49.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw0bf2e8ad/ProductImages/Face/Hydra_Touch_Powder_Foundation/hydratouchpowderfoundation_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 150,
    rating: 4.5,
    category: "Body Care",
  },
  {
    name_ar: "صابون طبيعي",
    name_en: "Natural Soap",
    description_ar: "صابون طبيعي للاستحمام برائحة عطرة",
    description_en: "Natural soap for bathing with fragrant scent",
    price: 19.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/b074403f4a1c12a7920199e4d8fabe78_ra,w158,h184_pa,w158,h184.jpg",
    available_quantity: 250,
    rating: 4.4,
    category: "Body Care",
  },
  {
    name_ar: "سكراب للجسم",
    name_en: "Body Scrub",
    description_ar: "سكراب للجسم لإزالة الخلايا الميتة",
    description_en: "Body scrub for removing dead skin cells",
    price: 39.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw2872d6ca/ProductImages/Eyes/Primal_Colors/primalcolors_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 140,
    rating: 4.6,
    category: "Body Care",
  },
  {
    name_ar: "زيت للجسم",
    name_en: "Body Oil",
    description_ar: "زيت طبيعي للجسم لترطيبه وإشراقه",
    description_en: "Natural body oil for moisturizing and glowing",
    price: 59.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw98d18f1b/ProductImages/Face/Stay_Matte_But_Not_Flat_Liquid_Foundation/staymattebutnotflatliquidfoundation_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 130,
    rating: 4.5,
    category: "Body Care",
  },
  {
    name_ar: "كريم اليدين",
    name_en: "Hand Cream",
    description_ar: "كريم اليدين لترطيب وحماية البشرة",
    description_en: "Hand cream for moisturizing and protecting skin",
    price: 29.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/8d1dc771f1dbdf2fe5e3cb378c44f1fb_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 180,
    rating: 4.5,
    category: "Body Care",
  },
  {
    name_ar: "كريم القدمين",
    name_en: "Foot Cream",
    description_ar: "كريم القدمين لترطيب وتنعيم البشرة",
    description_en: "Foot cream for moisturizing and softening",
    price: 34.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw91979480/ProductImages/Face/Rouge_Cream_Blush/rougecreamblush_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 160,
    rating: 4.4,
    category: "Body Care",
  },
  {
    name_ar: "جل الاستحمام",
    name_en: "Shower Gel",
    description_ar: "جل استحمام برائحة منعشة",
    description_en: "Shower gel with refreshing scent",
    price: 24.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/fd47eaa9241a010e48fc32cf4611d772_ra,w158,h184_pa,w158,h184.png",
    available_quantity: 200,
    rating: 4.5,
    category: "Body Care",
  },
  {
    name_ar: "مقشر للجسم",
    name_en: "Body Exfoliant",
    description_ar: "مقشر للجسم لإزالة الجلد الميت",
    description_en: "Body exfoliant for removing dead skin",
    price: 44.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwf8ec0855/ProductImages/Face/Radiant_Finishing_Powder/radiantfinishingpowder_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 145,
    rating: 4.6,
    category: "Body Care",
  },
  {
    name_ar: "مستحضر إزالة الشعر",
    name_en: "Hair Removal Cream",
    description_ar: "مستحضر لطيف لإزالة الشعر",
    description_en: "Gentle hair removal cream",
    price: 39.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw66d2b512/ProductImages/Face/Mineral_Finishing_Powder/800897815455_mineralfinishingpowder_lightmedium_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 170,
    rating: 4.5,
    category: "Body Care",
  },
  {
    name_ar: "مجموعة العناية بالجسم",
    name_en: "Body Care Set",
    description_ar: "مجموعة كاملة للعناية بالجسم",
    description_en: "Complete body care set",
    price: 129.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/e1e4b13a264fe9a7cbccaea373c24d9d_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 90,
    rating: 4.7,
    category: "Body Care",
  },
  // أدوات التجميل (10 منتجات)
  {
    name_ar: "فرشاة مكياج",
    name_en: "Makeup Brush Set",
    description_ar: "مجموعة فرش مكياج احترافية",
    description_en: "Professional makeup brush set",
    price: 79.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/d45c12626255b3ebd4d674060e1a38b3_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 120,
    rating: 4.6,
    category: "Beauty Tools",
  },
  {
    name_ar: "مرآة مكياج",
    name_en: "Makeup Mirror",
    description_ar: "مرآة مكياج مضيئة بتقنية LED",
    description_en: "LED lighted makeup mirror",
    price: 149.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/296c3f69ab7abdc797d6f0f7092f7a58_ra,w158,h184_pa,w158,h184.png",
    available_quantity: 80,
    rating: 4.7,
    category: "Beauty Tools",
  },
  {
    name_ar: "ملقط الحواجب",
    name_en: "Tweezers",
    description_ar: "ملقط احترافي لتشكيل الحواجب",
    description_en: "Professional tweezers for eyebrow shaping",
    price: 19.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/a7598160bc46504c98c26a241e3047e2_ra,w158,h184_pa,w158,h184.png",
    available_quantity: 220,
    rating: 4.5,
    category: "Beauty Tools",
  },
  {
    name_ar: "مشط للشعر",
    name_en: "Hair Comb",
    description_ar: "مشط عريض الأسنان للشعر",
    description_en: "Wide-tooth comb for hair",
    price: 14.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwbef45c94/ProductImages/Face/Conceal_Correct_Contour_Palette/800897831479_concealcorrectcontourpalette_light_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 250,
    rating: 4.4,
    category: "Beauty Tools",
  },
  {
    name_ar: "فرشاة الشعر",
    name_en: "Hair Brush",
    description_ar: "فرشاة شعر ناعمة لتسريح الشعر",
    description_en: "Soft hair brush for styling",
    price: 29.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/9ad93ab35e838c5a1669cc934c6d93b6_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 190,
    rating: 4.5,
    category: "Beauty Tools",
  },
  {
    name_ar: "ملف أظافر",
    name_en: "Nail File",
    description_ar: "ملف أظافر احترافي",
    description_en: "Professional nail file",
    price: 9.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/345fc4da3d9055f3742272714aace73b_ra,w158,h184_pa,w158,h184.png",
    available_quantity: 300,
    rating: 4.3,
    category: "Beauty Tools",
  },
  {
    name_ar: "مقص أظافر",
    name_en: "Nail Clippers",
    description_ar: "مقص أظافر عالي الجودة",
    description_en: "High quality nail clippers",
    price: 12.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/eea60b0c4f3b6539c1573415a610230d_ra,w158,h184_pa,w158,h184.jpg",
    available_quantity: 280,
    rating: 4.4,
    category: "Beauty Tools",
  },
  {
    name_ar: "إسفنجة مكياج",
    name_en: "Makeup Sponge",
    description_ar: "إسفنجة مكياج للاستخدام مع الأساس",
    description_en: "Makeup sponge for foundation application",
    price: 16.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/b9a2310c06b11611ab850051c90d06b0_ra,w158,h184_pa,w158,h184.jpeg",
    available_quantity: 240,
    rating: 4.5,
    category: "Beauty Tools",
  },
  {
    name_ar: "مجموعة أدوات التجميل",
    name_en: "Beauty Tools Set",
    description_ar: "مجموعة شاملة من أدوات التجميل",
    description_en: "Comprehensive beauty tools set",
    price: 99.99,
    image_url: "https://d3t32hsnjxo7q6.cloudfront.net/i/4448f8a937851a10afe049b1c374f448_ra,w158,h184_pa,w158,h184.jpg",
    available_quantity: 100,
    rating: 4.7,
    category: "Beauty Tools",
  },
  {
    name_ar: "حقيبة مكياج",
    name_en: "Makeup Bag",
    description_ar: "حقيبة أنيقة لحفظ أدوات المكياج",
    description_en: "Elegant bag for storing makeup tools",
    price: 34.99,
    image_url: "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw090ffa50/ProductImages/Face/High_Definition_Finishing_Power/800897834661_highdefinitionfinishingpowder_translucent_main.jpg?sw=390&sh=390&sm=fit",
    available_quantity: 160,
    rating: 4.5,
    category: "Beauty Tools",
  },
];

async function seed() {
  console.log("Starting seed for Husn Cosmetics Store...");

  // Insert categories
  console.log("Inserting categories...");
  const { data: insertedCategories, error: categoryError } = await supabase
    .from("categories")
    .insert(categories)
    .select();

  if (categoryError) {
    console.error("Error inserting categories:", categoryError);
    return;
  }

  console.log(`Inserted ${insertedCategories.length} categories`);

  // Map category names to IDs
  const categoryMap = new Map<string, string>();
  insertedCategories.forEach((cat) => {
    categoryMap.set(cat.name_en, cat.id);
  });

  // Insert products with category associations
  console.log("Inserting products...");
  const productsWithCategories = products.map((product) => {
    const categoryId = categoryMap.get((product as any).category) || null;
    const { category, ...productData } = product as any;

    return {
      ...productData,
      category_id: categoryId,
    };
  });

  const { data: insertedProducts, error: productError } = await supabase
    .from("gifts")
    .insert(productsWithCategories)
    .select();

  if (productError) {
    console.error("Error inserting products:", productError);
    return;
  }

  console.log(`Inserted ${insertedProducts.length} products`);
  console.log("Seed completed successfully!");
  console.log("\nCategories created:");
  insertedCategories.forEach((cat) => {
    console.log(`  - ${cat.name_en} (${cat.name_ar})`);
  });
}

seed().catch(console.error);
